FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . /app/

CMD ["streamlit", "run", "demo_app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]